"""Argus Approval Web Server.

Lightweight Flask server that provides a human-friendly UI for approving
or rejecting failover proposals generated by the monitoring engine.

Start with: python3 -m argus.cli serve
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

import structlog
from fastapi import FastAPI, Form, HTTPException
from fastapi.responses import FileResponse, RedirectResponse
from starlette.status import HTTP_303_SEE_OTHER

from .config.loader import load_config
from .engine import MonitoringEngine
from .persistence.database import Database, IncidentState

logger = structlog.get_logger(__name__)


def create_app(db_path: str = "argus.db", config_path: str = "monitor.config.yaml", dry_run: bool = True) -> FastAPI:
    """Create and configure the FastAPI approval server."""
    app = FastAPI(title="Argus", docs_url=None, redoc_url=None, openapi_url=None)
    app.state.db_path = db_path
    app.state.config_path = config_path
    app.state.dry_run = dry_run

    web_dir = Path(__file__).resolve().parent / "web"
    index_html = web_dir / "index.html"

    def _get_engine():
        cfg = load_config(app.state.config_path)
        db = Database(app.state.db_path)
        db.connect()
        return MonitoringEngine(config=cfg, db=db, dry_run=app.state.dry_run), db

    def _incident_to_dict(inc) -> dict[str, Any]:
        approval_available = False
        if inc.state.value == "awaiting_approval":
            db2 = Database(app.state.db_path)
            db2.connect()
            try:
                approval = db2.get_approval_for_incident(inc.id)
            finally:
                db2.close()
            approval_available = bool(approval and not approval.expired and not approval.approved_at)

        return {
            "id": inc.id,
            "app_id": inc.app_id,
            "app_name": inc.app_name,
            "region": inc.region,
            "health_score": inc.health_score,
            "health_status": inc.health_status.value,
            "state": inc.state.value,
            "created_at": inc.created_at.strftime("%Y-%m-%d %H:%M"),
            "summary": inc.summary,
            "approval_available": approval_available,
        }

    @app.get("/", response_class=FileResponse)
    def index():
        if not index_html.exists():
            raise HTTPException(status_code=500, detail="index.html not found")
        return FileResponse(index_html)

    @app.get("/healthz")
    def healthz() -> dict:
        return {"ok": True}

    @app.get("/api/status")
    def api_status() -> dict:
        return {"dry_run": bool(app.state.dry_run)}

    @app.get("/api/incidents")
    def list_incidents(limit: int = 50, app_id: Optional[str] = None) -> list[dict[str, Any]]:
        db = Database(app.state.db_path)
        db.connect()
        try:
            incidents = db.list_incidents(app_id=app_id, limit=limit)
        finally:
            db.close()
        return [_incident_to_dict(i) for i in incidents]

    @app.get("/api/incidents/{incident_id}")
    def get_incident(incident_id: str) -> dict[str, Any]:
        db = Database(app.state.db_path)
        db.connect()
        try:
            inc = db.get_incident_by_id(incident_id)
        finally:
            db.close()
        if not inc:
            raise HTTPException(status_code=404, detail="Incident not found")
        return _incident_to_dict(inc)

    @app.get("/api/incidents/{incident_id}/approval")
    def get_incident_approval(incident_id: str) -> dict[str, Any]:
        db = Database(app.state.db_path)
        db.connect()
        try:
            approval = db.get_approval_for_incident(incident_id)
        finally:
            db.close()

        if not approval or approval.expired or approval.approved_at:
            raise HTTPException(status_code=404, detail="No active approval for incident")

        return {
            "token": approval.token,
            "incident_id": approval.incident_id,
            "requested_at": approval.requested_at.isoformat(),
            "approved_at": approval.approved_at.isoformat() if approval.approved_at else None,
            "approved_by": approval.approved_by,
            "expired": bool(approval.expired),
        }

    @app.get("/api/approvals/{token}")
    def get_approval(token: str) -> dict[str, Any]:
        db = Database(app.state.db_path)
        db.connect()
        try:
            approval = db.get_approval_by_token(token)
        finally:
            db.close()
        if not approval:
            raise HTTPException(status_code=404, detail="Invalid approval token")
        return {
            "token": approval.token,
            "incident_id": approval.incident_id,
            "requested_at": approval.requested_at.isoformat(),
            "approved_at": approval.approved_at.isoformat() if approval.approved_at else None,
            "approved_by": approval.approved_by,
            "expired": bool(approval.expired),
        }

    @app.post("/api/approvals/{token}/approve")
    def approve_by_token(token: str, operator: str = "dashboard") -> dict[str, Any]:
        engine, db = _get_engine()
        try:
            result = engine.process_approval(token, approved_by=operator)
        finally:
            db.close()
        if not result.get("success"):
            raise HTTPException(status_code=400, detail=result.get("error", "Approval failed"))
        return result

    @app.post("/api/approvals/{token}/reject")
    def reject_by_token(token: str, operator: str = "dashboard") -> dict[str, Any]:
        db = Database(app.state.db_path)
        db.connect()
        try:
            approval = db.get_approval_by_token(token)
            if not approval:
                raise HTTPException(status_code=404, detail="Invalid approval token")
            incident = db.get_incident_by_id(approval.incident_id)
            if not incident:
                raise HTTPException(status_code=404, detail="Incident not found")
            if incident.state.value == "awaiting_approval":
                incident.state = IncidentState.RESOLVED
                incident.resolved_at = datetime.now(timezone.utc)
                db.save_incident(incident)
            approval.expired = True
            approval.approved_by = operator
            db.save_approval(approval)
        finally:
            db.close()

        return {"success": True}

    @app.post("/api/incidents/{incident_id}/approve")
    def approve_incident(incident_id: str, operator: str = "dashboard") -> dict[str, Any]:
        db = Database(app.state.db_path)
        db.connect()
        try:
            approval = db.get_approval_for_incident(incident_id)
        finally:
            db.close()
        if not approval or approval.expired or approval.approved_at:
            raise HTTPException(status_code=404, detail="No active approval for incident")
        return approve_by_token(approval.token, operator=operator)

    @app.post("/api/incidents/{incident_id}/reject")
    def reject_incident(incident_id: str, operator: str = "dashboard") -> dict[str, Any]:
        db = Database(app.state.db_path)
        db.connect()
        try:
            approval = db.get_approval_for_incident(incident_id)
        finally:
            db.close()
        if not approval or approval.expired or approval.approved_at:
            raise HTTPException(status_code=404, detail="No active approval for incident")
        return reject_by_token(approval.token, operator=operator)

    @app.get("/approve/{token}")
    def approve_page_compat(token: str):
        return RedirectResponse(url=f"/#approve={token}", status_code=HTTP_303_SEE_OTHER)

    @app.post("/approve/{token}")
    def approve_post_compat(
        token: str,
        action: str = Form("approve"),
        operator: str = Form("teams-approver"),
    ):
        if action == "reject":
            reject_by_token(token, operator=operator)
        else:
            approve_by_token(token, operator=operator)
        return RedirectResponse(url=f"/#approve={token}", status_code=HTTP_303_SEE_OTHER)

    return app
